FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    liblttng-ust1 \
    libkrb5-3 \
    zlib1g \
    libssl3 \
    libicu70 \
    curl \
    jq \
    ca-certificates \
    sudo \
    xz-utils


ARG GH_RUNNER_VERSION="2.301.1"
ARG TARGET_PLATFORM="x64"


WORKDIR /home/runner_user

RUN addgroup runner_group \
	&& adduser \
		--quiet \
		--disabled-password \
		--shell /bin/bash \
		--home /home/runner_user \
		--gecos "User" runner_user \
		--ingroup runner_group \
	&& chmod 0700 /home/runner_user \
	&& echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers


RUN mkdir /nix && chown runner_user:runner_group /nix

RUN mkdir /home/runner_user/_work && mkdir /home/runner_user/runner-cli

COPY ./ops/bash/install_runner.sh ./ops/bash/install_nix.sh ./ops/bash/runner_token.sh ./ops/bash/entrypoint.sh /home/runner_user
RUN chmod +x /home/runner_user/install_runner.sh /home/runner_user/runner_token.sh /home/runner_user/entrypoint.sh /home/runner_user/install_nix.sh

RUN ls -la /home/runner_user/
RUN ls -la /home/runner_user/runner-cli
#
# RUN /home/runner_user/install_runner.sh ${GH_RUNNER_VERSION} ${TARGET_PLATFORM} \
#   && rm /home/runner_user/install_runner.sh



RUN chown --recursive runner_user:runner_group /home/runner_user
USER runner_user

RUN ls -la /home/runner_user/
RUN ls -la /home/runner_user/runner-cli

# ENV HOME=/home/runner_user
# RUN /home/runner_user/install_nix.sh \
#   && rm /home/runner_user/install_nix.sh

ENTRYPOINT ["./entrypoint.sh"]
CMD ["./runner-cli/bin/Runner.Listener", "run", "--startuptype", "service"]
