FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    liblttng-ust1 \
    libkrb5-3 \
    zlib1g \
    libssl3 \
    libicu70 \
    curl \
    jq \
    ca-certificates \
    sudo \
    xz-utils


ARG GH_RUNNER_VERSION="2.301.1"
ARG TARGET_PLATFORM="x64"


WORKDIR /home/runner_user

RUN addgroup runner_group \
	&& adduser \
		--quiet \
		--disabled-password \
		--shell /bin/bash \
		--home /home/runner_user \
		--gecos "User" runner_user \
		--ingroup runner_group \
	&& chmod 0700 /home/runner_user \
	&& echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers


RUN mkdir /nix && chown runner_user:runner_group /nix

# ENV HOME=/home/runner_user
# RUN BASE_URL='https://raw.githubusercontent.com/ES-Nix/get-nix/' \
# 	&& SHA256=5443257f9e3ac31c5f0da60332d7c5bebfab1cdf \
# 	&& NIX_RELEASE_VERSION='2.10.2' \
# 	&& curl -fsSL "${BASE_URL}""$SHA256"/get-nix.sh | sh -s -- ${NIX_RELEASE_VERSION} \
# 	&& . "$HOME"/.nix-profile/etc/profile.d/nix.sh \
# 	&& . ~/."$(ps -ocomm= -q $$)"rc \
# 	&& export TMPDIR=/tmp \
# 	&& nix flake --version
# 	echo "$HOME"/.nix-profile/bin >> $GITHUB_PATH

RUN mkdir /home/runner_user/_work && mkdir /home/runner_user/runner-cli

COPY ./ops/bash/install_runner.sh /home/runner_user

RUN chmod +x /home/runner_user/install_runner.sh

COPY ./ops/bash/runner_token.sh ./ops/bash/entrypoint.sh /home/runner_user
RUN chmod +x /home/runner_user/runner_token.sh /home/runner_user/entrypoint.sh

RUN ls -la /home/runner_user/
RUN ls -la /home/runner_user/runner-cli

RUN /home/runner_user/install_runner.sh ${GH_RUNNER_VERSION} ${TARGET_PLATFORM} \
  && rm /home/runner_user/install_runner.sh

RUN chown --recursive runner_user:runner_group /home/runner_user
USER runner_user

RUN ls -la /home/runner_user/
RUN ls -la /home/runner_user/runner-cli

ENTRYPOINT ["./entrypoint.sh"]
CMD ["./runner-cli/bin/Runner.Listener", "run", "--startuptype", "service"]
