apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: busybox
    command: ['sh', '-c', "while ! false; do echo $(date +'%d/%m/%Y %H:%M:%S:%3N'); sleep 1; done"]
